<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="TEST" Id="{9e6940e2-7b3f-425d-b76c-928c06cc9bd2}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM TEST
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[GVL.ENCODER_1_RAW_COUNTS;]]></ST>
    </Implementation>
    <LineIds Name="TEST">
      <LineId Id="5" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>